M48
; DRILL file {KiCad 9.0.6} date 2026-03-06T12:51:15-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-06T12:51:15-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X89.7Y-67.7
X89.7Y-112.4
X149.4Y-67.7
X149.4Y-112.4
T2
X222.6Y-87.6
M30
